#!/bin/sh

tags=`echo $@ | awk '{OFS="|";$1=$1;$0=tolower($0);print}'`

echo $tags

if [ ! -f "${workdir}/.papermeta" ]; then
  touch "${workdir}/.papermeta"
fi

cat ${workdir}/.papermeta | awk -F"---" '{
  if (tolower($5) ~ /'$tags'/) {
    printf "%s : %s (Tag: %s)\n", $1, $2, $5
  }
}'
