#!/bin/sh

getname() {
  hash=$1
  cat ${workdir}/.papermeta | grep $hash | awk -F"---" '{print $2}'
}

if [ ! -f "${workdir}/.paperdb" ]; then
  ${scriptdir}/updatedb
fi

keyword="$@"

hashes=`cat ${workdir}/.papermeta | grep -iE "$keyword" | awk -F"---" '{print $1}'`

if [ -z "$hashes" ]; then
  printf "[-] Not found\n"
  exit 1
fi

printf "[+] %d paper(s) found.\n" "`echo \"$hashes\" | wc -l`"

for x in $hashes; do
  name=`getname $x`
  printf "%s : %s\n" $x "$name"
done
