#!/bin/sh

getname() {
  hash=$1
  basename "`cat ${workdir}/.paperdb | grep $hash | awk '{ print substr($0, 42); }'`" | sed 's/\.pdf//g'
}

if [ ! -f '.paperdb' ]; then
  ${scriptdir}/updatedb
fi

keyword="$@"

hashes=`cat ${workdir}/.paperdb | grep -iE "$keyword" | cut -f1`

printf "[+] %d paper(s) found.\n" "`echo -n \"$hashes\" | wc -l`"

for x in $hashes; do
  name=`getname $x`
  printf "%s : %s\n" $x "$name"
done
