#!/bin/sh

temp="/tmp/hashes.tmp"
cat ${workdir}/.papermeta | awk -F"---" '{print $1}' | sort > $temp

cat ${workdir}/.paperdb               |
  cut -f1                             |
  diff $temp -                        |
  grep -E "> [0-9a-f]"                |
  sed 's/.\s\([0-9a-f]\+\)/\1/g'      |
  xargs -I {} 'grep' '{}' '.paperdb'  |
  awk -F'\t' '{
    file = $2;
    sub(/^.*\//, "", file);
    sub(".pdf", "", file);
    print $1 "---" file
}' >> ${workdir}/.papermeta

cp ${workdir}/.papermeta ${workdir}/.papermeta.work

for x in `cat ${workdir}/.papermeta | awk -F'---' '{print $1}'`; do
  if [ "`grep $x ${workdir}/.paperdb`" = "" ]; then
    grep -v $x .papermeta.work > "${workdir}/.papermeta.work.2"
    mv "${workdir}/.papermeta.work.2" "${workdir}/.papermeta.work"
  fi
done

mv ${workdir}/.papermeta.work ${workdir}/.papermeta

rm $temp
