#!/bin/sh

if [ $# -lt 1 ]; then
  echo "Usage: $0 [grep/grep_tag/open/updatedb/updatemeta/status/description]"
  exit 1
fi

export "workdir"="`pwd`"
export "scriptdir"="`pwd`/.script"
cmd_name=$1
if [ -f "./.script/$cmd_name" ]; then
  shift 1
  ./.script/$cmd_name $@
elif [ "`grep -iE \"$1\" .paperdb | wc -l`" -eq "1" ]; then
  ./.script/open "$1"
else
  echo "Error: Invalid Argument: \"$@\"" >&2
  echo "Candidate: " >&2
  ./.script/grep $@ >&2
fi
unset workdir
unset scriptdir
